In [1]:
#Import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Import dataset
dataset = pd.read_csv('Train.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[ 0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [-0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 ...
 [ 1.04417694 -0.89920649  1.73039905 -1.87105676  0.44251965]
 [-1.2691729  -0.00505216  1.85766873 -1.08036482  0.73633394]
 [-1.88400025 -0.84942743 -1.45227035  0.48861308  1.4595758 ]]


In [7]:
print(y)

[ -82.15466656  -48.89796018   77.2703707  ... -107.51050797  -47.34155781
 -115.93900296]


In [9]:
#Training MLR model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
#Import test dataset
dataset = pd.read_csv('Test.csv')
X_test = dataset

In [14]:
#Prediction of test set results
y_pred = regressor.predict(X_test)

In [16]:
#Print results in a vertical format 
#reshape used to display them vertically
#second argument of concatenate function is 0/1 => vert/horiz concatenation. since 2 vert columns will join to give horiz => 1
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[ 1.15e+02 -9.81e-01]
 [ 1.18e+02 -3.55e-01]
 [-2.17e+01  4.55e-01]
 [-4.39e+01 -1.31e+00]
 [-9.59e+01  4.12e-01]
 [-4.45e+01  3.35e-01]
 [-7.56e+01 -1.04e+00]
 [ 2.38e+01 -5.86e-01]
 [ 1.74e+02  2.12e-01]
 [ 1.73e+02 -8.56e-01]
 [-1.05e+02 -1.18e-01]
 [-2.08e+01  1.01e+00]
 [-3.91e+00 -8.47e-01]
 [ 1.23e+02 -3.61e-01]
 [ 4.03e+01  1.08e+00]
 [ 4.57e+01  7.21e-01]
 [-1.90e+02 -1.89e-01]
 [ 2.26e+01 -1.26e+00]
 [ 1.16e+01 -4.58e-01]
 [ 1.36e+02  5.68e-01]
 [ 6.49e+01  6.58e-01]
 [-6.20e+01  9.08e-02]
 [-1.08e+02  4.36e-01]
 [-7.41e+00  2.68e-01]
 [-5.85e+01  1.56e+00]
 [ 1.19e+01 -2.47e-01]
 [ 2.92e+01  4.46e-01]
 [ 1.08e+02  1.41e-01]
 [ 2.41e+01  1.34e-01]
 [-2.61e+01 -1.71e+00]
 [ 1.11e+02  2.87e+00]
 [-4.49e+01 -3.10e-02]
 [ 2.17e+02  1.01e-01]
 [-1.39e+01 -1.35e+00]
 [-2.29e+02  3.05e-02]
 [ 1.55e+02 -9.67e-01]
 [-2.23e+00  6.33e-01]
 [ 1.27e+01 -1.27e+00]
 [-3.08e+02  2.06e-01]
 [ 7.71e+01  2.58e+00]
 [-8.12e+01  3.65e-01]
 [-2.07e+02 -4.07e-02]
 [-2.39e+02  9.95e-01]
 [ 1.35e+02

In [18]:
#Making a single prediction
print(regressor.predict([[1.0152538748373274,2.0762094382543737,-0.26643481961981624,-2.418088204228289,-0.9805027900004764]]))
#values of the features were all input in a double pair of square brackets
#Since "predict" method always expects a 2D array as the format of its inputs

[114.58]


In [19]:
#Final Linear Regression equation with coeff values
print(regressor.coef_)
print(regressor.intercept_)

[29.68 92.66  8.28 44.77  2.52]
4.990966735574959
